params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  network:
    name: actor_critic
    separate: True
    space: 
      discrete:
      
    mlp:
      units: [512, 256, 128]
      activation: relu
      initializer:
        name: default 
      regularizer:
        name: 'None'
  config:
    name: 2c_vs_64zg_neg
    reward_shaper:
      scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    score_to_win: 1000
    grad_norm: 0.5
    entropy_coef: 0.005
    truncate_grads: True
    env_name: smac
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    horizon_length: 128
    minibatch_size: 1024
    mini_epochs: 4
    critic_coef: 1
    lr_schedule: None
    kl_threshold: 0.05
    normalize_input: True
    use_action_masks: True

    env_config:
      name: 2c_vs_64zg
      frames: 1
      random_invalid_step: False
      central_value: True
      reward_only_positive: False
      state_last_action: True

    central_value_config:
      minibatch_size: 512
      mini_epochs: 4
      learning_rate: 5e-4
      clip_value: False
      normalize_input: True
      network:
        name: actor_critic
        central_value: True
        mlp:
          units: [512, 256, 128]
          activation: relu
          initializer:
            name: default
            scale: 2 
          regularizer:
            name:  'None'
