params:
  seed: 7

  #devices: [0, 0]

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: tcnnnet

    encoding:
      otype: "Identity"

    network:
      type: "FullyFusedMLP"
      activation: "ReLU"
      output_activation: "None"
      n_neurons: 128
      n_hidden_layers: 4

  config:
    name: Ant_brax_tcnn
    env_name: brax
    multi_gpu: False
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: 1000
    save_best_after: 100
    save_frequency: 50
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 8
    num_actors: 4096
    minibatch_size: 32768
    mini_epochs: 5
    critic_coef: 2
    clip_value: False
    bounds_loss_coef: 0.0001

    env_config:
      env_name: 'ant'
