params:
  seed: 7

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [512, 256, 128]
      activation: elu
      d2rl: False
      
      initializer:
        name: default
      regularizer:
        name: None

  config:
    name: Humanoid_brax
    full_experiment_name: Humanoid_brax
    env_name: brax
    multi_gpu: False
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    normalize_advantage: True
    use_smooth_clamp: True
    reward_shaper:
      scale_value: 1.0
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: 1000
    save_best_after: 100
    save_frequency: 50
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 16
    num_actors: 4096
    minibatch_size: 32768
    mini_epochs: 5
    critic_coef: 2

    clip_value: True
    bound_loss_type: regularisation
    bounds_loss_coef: 0.0

    env_config:
      env_name: humanoid