params:  
  algo:
    name: sac

  model:
    name: soft_actor_critic

  network:
    name: soft_actor_critic
    separate: True
    space:
      continuous:
    mlp:
      units: [256, 128, 64]
      activation: relu
      
      initializer:
        name: default
    log_std_bounds: [-5, 2]

  load_checkpoint: False
  load_path: nn/Ant.pth

  config:
    name: 'Ant_brax'
    env_name : brax
    normalize_input: True
    reward_shaper:
      scale_value: 1
    device: cuda
    max_epochs: 2000000
    num_steps_per_episode: 128
    save_best_after: 100
    save_frequency: 10000
    gamma: 0.99
    init_alpha: 1
    alpha_lr: 0.005
    actor_lr: 0.0005
    critic_lr: 0.0005
    critic_tau: 0.005
    batch_size: 4096
    learnable_temperature: true
    num_seed_steps: 5
    replay_buffer_size: 1000000
    num_actors: 128

    env_config:
      env_name: 'ant'