params:
  seed: 322
  algo:
    name: mbppo_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
          scale: 0.02
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [64, 64]
      activation: relu
      initializer:
          name: default

  model_network:
    name: env_model
    mlp:
      units: [128, 128, 128]
      activation: relu
      initializer:
          name: default

  config:
      reward_shaper:
        scale_value: 0.1
      normalize_advantage: True
      gamma: 0.99
      tau: 0.9

      learning_rate: 1e-4
      name: LunarLander_model_based
      score_to_win: 300

      grad_norm: 0.5
      entropy_coef: 0.0
      truncate_grads: True
      env_name: envpool
      ppo: true
      e_clip: 0.2
      clip_value: True
      num_actors: 16
      horizon_length: 128
      minibatch_size: 256
      mini_epochs: 4
      critic_coef: 1
      lr_schedule: None #adaptive
      kl_threshold: 0.008
      schedule_type: standard
      normalize_input: False
      seq_length: 4
      bounds_loss_coef: 0
      env_config:
        env_name: LunarLanderContinuous-v2
      player:
        render: True

  model_training_config:
      minibatch_size: 2048
      mini_epochs: 4
      learning_rate: 1e-3
      replay_buffer_size: 8192 #1048576 # 1024 * 1024
      weight_decay: 1e-5
      hold_out: 0.1
