params:  
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          # pytorch
          name: default
          scale: 0.02

          # tf
        #  name: normc_initializer
        #  std: 0.01
        sigma_init:
          name: const_initializer     
          #  value: 0 # tf
          val: 0 # pytorch

        fixed_sigma: True
    mlp:
      units: [128, 64]
      activation: elu

      initializer:
        # pytorch
          name: default
          scale: 2

      # tf
      #  name: normc_initializer
      #  std: 1
      regularizer:
        name:  'None' #'l2_regularizer'
        #scale: 0.001

  load_checkpoint: False
  load_path: path

  config:
    reward_shaper:
      scale_value: 0.01
    normalize_advantage : True
    gamma : 0.99
    tau : 0.95
    learning_rate : 3e-4
    name : 'ant_torch'
    score_to_win : 20000
    grad_norm : 2.5
    entropy_coef : 0.0
    truncate_grads : True
    env_name : FlexAnt
    ppo : True
    e_clip : 0.2
    num_actors : 256
    horizon_length : 16
    minibatch_size : 4096
    mini_epochs : 8
    critic_coef : 2
    clip_value : False
    lr_schedule : adaptive
    kl_threshold : 0.01
    normalize_input : True
    normalize_value : True
    bounds_loss_coef: 0.0001
