params:  
  seed: 8
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256,128,64]
      d2rl: False
      activation: elu
      initializer:
        name: default
    rnn:
      name: 'gru'
      units: 64
      layers: 1
      before_mlp: False
      #concat_input: True
      #layer_norm: True

  config:
    env_name: BipedalWalker-v3
    name: walker_rnn
    reward_shaper:
      min_val: -1
      scale_value: 0.1

    normalize_advantage: True
    gamma: 0.995
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    kl_threshold: 0.004
    save_best_after: 10
    score_to_win: 300
    grad_norm: 1.5
    entropy_coef: -0.003
    truncate_grads: True
    e_clip: 0.2
    clip_value: False
    num_actors: 16
    horizon_length: 256
    minibatch_size: 2048
    mini_epochs: 4
    critic_coef: 2
    normalize_input: True
    bound_loss_type: regularisation
    bounds_loss_coef: 0.001
    max_epochs: 10000
    seq_length: 32
    normalize_value: True
    use_diagnostics: True
    value_bootstrap: True
    weight_decay: 0.0001
    use_smooth_clamp: True

    player:
      render: True
      deterministic: True
      games_num: 200
