params:
  seed: 7
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [512, 256, 128]
      activation: elu
      initializer:
        name: default

  config:
      name: DMSoccerEnv-v0
      env_name: SelfPlaySoccerVecEnv
      ppo: True
      score_to_win: 20000
      normalize_input: True
      normalize_value: True
      value_bootstrap: False
      reward_shaper:
        scale_value: 1
      normalize_advantage: True
      gamma: 0.99
      tau: 0.95

      learning_rate: 3e-4
      lr_schedule: None #adaptive
      kl_threshold: 0.008
      schedule_type: standard

      grad_norm: 1.0
      entropy_coef: 0.0
      truncate_grads: True
      e_clip: 0.2
      clip_value: True
      use_smooth_clamp: True
      bound_loss_type: regularisation
      bounds_loss_coef: 0.0000

      max_epochs: 25000
      num_actors: 16
      horizon_length: 64
      minibatch_size: 512
      mini_epochs: 5
      critic_coef: 2
      save_frequency: 400
      full_experiment_name: 'soccer_sp'
      env_config:
        op_bot: 'random' #'runs/soccer_sp/nn/last_DMSoccerEnv-v0_ep_1800_rew_0.36018568.pth'
        net_path: 'runs/soccer_sp/nn/'
        config_path: 'rl_games/configs/dm_control/soccer.yaml'
        use_reward_diff: True

      player:
        render: True
        deterministic: False