params:
  seed: 5
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      initializer:
        name: default

  config:
      name: WalkerStand_envpool
      env_name: envpool
      score_to_win: 20000
      normalize_input: True
      normalize_value: True
      value_bootstrap: False
      reward_shaper:
        scale_value: 1
        shift_value: 1
        log_val: True
      normalize_advantage: True
      gamma: 0.99
      tau: 0.95

      learning_rate: 3e-4
      lr_schedule: adaptive
      kl_threshold: 0.008
      grad_norm: 1.0
      entropy_coef: 0.0
      truncate_grads: True
      e_clip: 0.2
      clip_value: False
      use_smooth_clamp: False
      bound_loss_type: regularisation
      bounds_loss_coef: 0.001
      max_epochs: 4000
      num_actors: 64
      horizon_length: 128
      minibatch_size: 2048
      mini_epochs: 5
      critic_coef: 4
      use_diagnostics: True
      env_config:
        env_name: WalkerStand-v1
        flatten_obs: True

      player:
        render: False
      