params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  load_checkpoint: False
  load_path: 'nn/6h_vs_8z_cnn'

  network:
    name: actor_critic
    separate: True
    #normalization: layer_norm
    space: 
      discrete:
      
    cnn:
      type: conv1d
      activation: relu
      initializer:
        name: variance_scaling_initializer
        scale: 2
      regularizer:
        name: 'None'
      convs:    
            - filters: 256
              kernel_size: 3
              strides: 1
              padding: 1
            - filters: 512
              kernel_size: 3
              strides: 2
              padding: 1
            - filters: 1024
              kernel_size: 3
              strides: 2
              padding: 1
    mlp:
      units: [256, 128]
      activation: relu
      initializer:
        name: variance_scaling_initializer
        scale: 2 
      regularizer:
        name:  'None'
  config:
    name: 6h_vs_8z_cnn
    reward_shaper:
        scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-4
    score_to_win: 20
    grad_norm: 0.5
    entropy_coef: 0.005
    truncate_grads: True
    env_name:  smac_cnn
    ppo: true
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    steps_num: 128
    minibatch_size: 3072
    mini_epochs: 3
    critic_coef: 2
    lr_schedule:  None
    lr_threshold: 0.05
    normalize_input: False
    seq_len: 2
    use_action_masks: True
    ignore_dead_batches : False

    env_config:
      name: 6h_vs_8z
      frames: 4
      transpose: False
      random_invalid_step: False
      central_value: True

    central_value_config:
      minibatch_size: 512
      mini_epochs: 4
      lr: 5e-4
      clip_value: False
      normalize_input: False
      network:
        name: actor_critic
        central_value: True
        cnn:
          type: conv1d
          activation: relu
          initializer:
            name: variance_scaling_initializer
            scale: 2
          regularizer:
            name: 'None'
          convs:    
            - filters: 256
              kernel_size: 3
              strides: 1
              padding: 1
            - filters: 512
              kernel_size: 3
              strides: 2
              padding: 1
            - filters: 1024
              kernel_size: 3
              strides: 2
              padding: 1
        mlp:
          units: [256, 128]
          activation: relu
          initializer:
            name: variance_scaling_initializer
            scale: 2 
          regularizer:
            name:  'None'