params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  network:
    name: resnet_actor_critic
    require_rewards: True
    require_last_actions: True
    separate: False
    value_shape: 1
    space: 
      discrete:
    
    cnn:
      permute_input: True
      conv_depths: [16, 32, 32]
      activation: relu
      initializer:
        name: default
      regularizer:
        name: 'None'
      
    mlp:
      units: [512]
      activation: relu
      regularizer:
        name: 'None'
      initializer:
        name: default 
    rnn:
      name: lstm
      units: 256
      layers: 1
  config:
    reward_shaper:
      min_val: -1
      max_val: 1
        
    normalize_advantage: True
    gamma: 0.995
    tau: 0.95
    learning_rate: 3e-4
    name: mario_resnet
    score_to_win: 100000
    grad_norm: 1.5
    entropy_coef: 0.01
    truncate_grads: True
    env_name: MarioEnv
    e_clip: 0.2
    clip_value: True
    num_actors: 16
    horizon_length: 256
    minibatch_size: 2048
    mini_epochs: 2
    critic_coef: 1
    lr_schedule: None
    kl_threshold: 0.01
    normalize_input: False
    use_diagnostics: True
    seq_length: 32
    max_epochs: 200000

    env_config:
      use_dict_obs_space: True

    player:
        render: False
        games_num: 20
        n_game_life: 5
        deterministic: True

