
params:  
  seed: 322
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  network:
    name: resnet_actor_critic
    require_rewards: False
    require_last_actions: False
    separate: False
    value_shape: 1
    space: 
      discrete:
    
    cnn:
      conv_depths: [32, 64, 128, 256]
      activation: relu
      initializer:
        name: default
      regularizer:
        name: 'None'
      
    mlp:
      units: [512]
      activation: relu
      regularizer:
        name: 'None'
      initializer:
        name: default 
    
  config:
    name: mario_ray
    env_name: 'SuperMarioBrosRandomStages-v1'
    score_to_win: 100500
    normalize_value: True
    normalize_input: False
    reward_shaper:
      scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    grad_norm: 1.0
    entropy_coef: 0.005
    truncate_grads: True
    learning_rate: 3e-4
    lr_schedule: adaptive
    kl_threshold: 0.01
    grad_norm: 1.0
    entropy_coef: 0.01
    e_clip: 0.2
    clip_value: False
    num_actors: 64
    horizon_length: 128
    # seq_length: 8
    minibatch_size: 4096
    mini_epochs: 4
    critic_coef: 2
    max_epochs: 5000
    use_diagnostics: False


    player:
      render: True
      games_num: 1
      n_game_life: 1
      deterministic: False
      use_vecenv: False
      render_sleep: 0.05