params:  
  #seed: 322
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  network:
    name: actor_critic
    separate: False
    space: 
      discrete:

    cnn:
      #permute_input: False
      type: conv2d
      activation: relu
      initializer:
        name: default
        #name: glorot_normal_initializer
        #gain: 1.4142
      regularizer:
        name: None
      convs:    
        - filters: 32
          kernel_size: 8
          strides: 4
          padding: 0
        - filters: 64
          kernel_size: 4
          strides: 2
          padding: 0
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 0
      
    mlp:
      units: [512]
      activation: relu
      initializer:
        name: orthogonal_initializer
        gain: 1.41421356237

  config:
    name: mario_ray
    env_name: 'SuperMarioBrosRandomStage1-v1'
    score_to_win: 100500
    normalize_value: True
    normalize_input: False
    reward_shaper:
      #min_val: -1
      #max_val: 1
      scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    grad_norm: 1.0
    entropy_coef: 0.01
    truncate_grads: True
    learning_rate: 3e-4
    lr_schedule: None #adaptive
    kl_threshold: 0.01
    grad_norm: 1.0
    entropy_coef: 0.01
    e_clip: 0.2
    clip_value: False
    num_actors: 16
    horizon_length: 128
    minibatch_size: 1024
    mini_epochs: 4
    critic_coef: 2
    max_epochs: 5000
    use_diagnostics: False


    player:
      render: True
      games_num: 100
      n_game_life: 3
      deterministic: False
      use_vecenv: False
      render_sleep: 0.05