params:  
  seed: 322
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  network:
    name: actor_critic
    separate: False
    space: 
      discrete:

    cnn:
      type: conv2d
      activation: elu
      initializer:
        name: glorot_normal_initializer
        gain: 1.4142
      regularizer:
        name: None
      convs:    
        - filters: 32
          kernel_size: 8
          strides: 4
          padding: 0
        - filters: 64
          kernel_size: 4
          strides: 2
          padding: 0
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 0
    
    mlp:
      units: [512]
      activation: elu
      initializer:
        name: orthogonal_initializer
        gain: 1.41421356237
    # rnn:
    #   before_mlp: False
    #   name: lstm
    #   units: 512
    #   layers: 1
    #   layer_norm: True

  config:
    name: mario_ray
    env_name: 'SuperMarioBros-v1'
    score_to_win: 2000000.0
    normalize_value: True
    normalize_input: False
    reward_shaper:
      min_val: -1
      max_val: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    grad_norm: 0.5
    entropy_coef: 0.01
    truncate_grads: True
    learning_rate: 5e-4
    lr_schedule: linear
    seq_length: 16
    kl_threshold: 0.01
    grad_norm: 1.0
    entropy_coef: 0.01
    truncate_grads: True
    e_clip: 0.2
    clip_value: False
    num_actors: 64
    horizon_length: 256
    minibatch_size: 8192
    mini_epochs: 4
    critic_coef: 1
    max_epochs: 5000
    use_diagnostics: False


    player:
      render: True
      games_num: 1
      n_game_life: 1
      deterministic: True