params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  network:
    name: actor_critic
    separate: False
    #normalization: layer_norm
    space: 
      discrete:

    mlp:
      units: [512, 256]
      activation: relu
      initializer:
        name: default 
      regularizer:
        name:  'None'
    rnn:
      name: lstm
      units: 128
      layers: 1
      layer_norm: False

  config:
    name: 5m_vs_6m_rnn_cv
    reward_shaper:
      scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    score_to_win: 20
    entropy_coef: 0.005
    truncate_grads: True
    grad_norm: 2
    env_name: smac
    e_clip: 0.2
    clip_value: False
    num_actors: 24
    horizon_length: 256
    minibatch_size: 2560 # 5 * 512
    mini_epochs: 4
    critic_coef: 1
    lr_schedule: None
    kl_threshold: 0.05
    normalize_input: True
    normalize_value: False
    use_action_masks: True
    seq_length: 16
    #max_epochs: 10000
    
    env_config:
      name: 5m_vs_6m
      central_value: True
      reward_only_positive: True
      obs_last_action: False
      apply_agent_ids: True

    player:
      render: False
      games_num: 200
      n_game_life: 1
      deterministic: True

    central_value_config:
      minibatch_size: 512
      mini_epochs: 4
      learning_rate: 5e-4
      clip_value: False
      normalize_input: True
      truncate_grads: True
      grad_norm: 2
      network:
        #normalization: layer_norm
        name: actor_critic
        central_value: True
        mlp:
          units: [512, 256]
          activation: relu
          initializer:
            name: default
            scale: 2 
          regularizer:
            name:  'None'
        rnn:
          name: lstm
          units: 128
          layers: 1
          layer_norm: False
      
      #reward_negative_scale: 0.1