params:
  seed: 5
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [512, 256, 128]
      activation: elu
      initializer:
        name: default

  config:
      name: MyoHandReorient8
      env_name: myosuite_gym
      #score_to_win: 20000
      mixed_precision: True
      normalize_input: True
      normalize_value: True
      value_bootstrap: True
      reward_shaper:
        scale_value: 1
        #shift_value: 1
        log_val: False
      normalize_advantage: True
      gamma: 0.99
      tau: 0.95
      learning_rate: 3e-4
      lr_schedule: adaptive
      kl_threshold: 0.008
      grad_norm: 1.0
      entropy_coef: 0.0
      truncate_grads: True
      e_clip: 0.2
      clip_value: True
      use_smooth_clamp: False
      bound_loss_type: regularisation
      bounds_loss_coef: 0.001
      max_epochs: 10000
      #max_frames: 100_000_000
      num_actors: 2
      horizon_length: 128
      minibatch_size: 128 #2048
      mini_epochs: 5
      critic_coef: 4
      use_diagnostics: False
      env_config:
        env_name: myoFingerPoseRandom-v0 #myoHandReorient8-v0
        flatten_obs: True

      player:
        render: False
      