params:  
  seed: 42
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      d2rl: False
      activation: elu
      initializer:
        name: default
        scale: 2
  config:
    env_name: myo_gym
    name: MyoElbowPose1D6MRandom
    reward_shaper:
      scale_value: 1.0
      #shift_value: 1.0
      #min_val: 0
      log_val: False
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    save_best_after: 50
    grad_norm: 1.5
    entropy_coef: 0
    truncate_grads: True
    e_clip: 0.2
    clip_value: False
    num_actors: 32
    horizon_length: 128
    minibatch_size: 2048
    mini_epochs: 4
    critic_coef: 2
    bounds_loss_coef: 0.001
    max_epochs: 1000
    use_diagnostics: True
    weight_decay: 0.0
    use_smooth_clamp: True
    env_config:
      name: myoElbowPose1D6MRandom-v0
    player:
      render: True
      deterministic: True
      games_num: 200
