params:
  seed: 42
  algo:
    name: a2c_continuous
  model:
    name: continuous_a2c_logstd
  network:
    name: actor_critic
    separate: false
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: true
        min_sigma: 0.15
    mlp:
      units:
      - 512
      - 256
      - 128
      activation: elu
      initializer:
        name: default
  config:
    name: MJLab_Lift_Cube_Yam
    env_name: mjlab_lift_cube_yam
    normalize_input: true
    normalize_value: true
    value_bootstrap: true
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: true
    gamma: 0.99
    tau: 0.95
    learning_rate: 0.001
    lr_schedule: adaptive
    grad_norm: 1.0
    entropy_coef: 0.005
    truncate_grads: true
    e_clip: 0.2
    clip_value: false
    num_actors: 4096
    horizon_length: 24
    minibatch_size: 24576
    mini_epochs: 5
    critic_coef: 1
    use_smooth_clamp: false
    bound_loss_type: regularisation
    bounds_loss_coef: 0.0001
    device: cuda:0
    max_epochs: 5000
    env_config:
      task_name: Mjlab-Lift-Cube-Yam
      device: cuda
    player:
      render: false
    save_frequency: 500
    clip_actions: false
    central_value_config:
      minibatch_size: 24576
      mini_epochs: 5
      learning_rate: 0.001
      kl_threshold: 0.01
      clip_value: true
      normalize_input: true
      network:
        name: actor_critic
        central_value: true
        mlp:
          units:
          - 512
          - 256
          - 128
          activation: elu
          initializer:
            name: default
    kl_threshold: 0.01
