params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  network:
    name: actor_critic
    separate: True
    #normalization: layer_norm
    space: 
      discrete: 

    cnn:
      type: conv1d

      activation: relu
      initializer:
        name: glorot_uniform_initializer
        gain: 1 
      regularizer:
        name: 'None'
      convs:    
        - filters: 64
          kernel_size: 3
          strides: 2
          padding: 1
        - filters: 128
          kernel_size: 3
          strides: 1
          padding: 0
        - filters: 256
          kernel_size: 3
          strides: 1
          padding: 0
    mlp:
      units: [256, 128]
      activation: relu
      initializer:
        name: glorot_uniform_initializer
        gain: 1 
      regularizer:
        name:  'None'
  config:
    name: 3m
    reward_shaper:
        scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    score_to_win: 20
    grad_norm: 0.5
    entropy_coef: 0.005
    truncate_grads: True
    env_name: smac_cnn
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    horizon_length: 128
    minibatch_size: 1536
    mini_epochs: 1
    critic_coef: 1
    lr_schedule:  None
    kl_threshold: 0.05
    normalize_input: True
    seq_length: 2
    use_action_masks: True

    env_config:
      name: 3m
      frames: 4
      transpose: True
      random_invalid_step: True
  
