params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  network:
    name: actor_critic
    separate: True
    #normalization: layer_norm
    space: 
      discrete:

    mlp:
      units: [512, 256]
      activation: relu
      initializer:
        name: default 
      regularizer:
        name:  'None'
    rnn:
      name: lstm
      units: 128
      layers: 1
      layer_norm: True
  config:
    name: 5m_vs_6m_rnn
    reward_shaper:
      scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-4
    score_to_win: 20
    entropy_coef: 0.005
    truncate_grads: True
    grad_norm: 1.5
    env_name: smac
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    horizon_length: 128
    minibatch_size: 2560 # 5 * 512
    mini_epochs: 4
    critic_coef: 1
    lr_schedule: None
    kl_threshold: 0.05
    normalize_input: True
    normalize_value: False
    use_action_masks: True
    seq_length: 8
    #max_epochs: 10000
    env_config:
      name: 5m_vs_6m
      central_value: False
      reward_only_positive: True
      obs_last_action: True
      apply_agent_ids: False

    player:
      render: False
      games_num: 200
      n_game_life: 1
      deterministic: True
      
      #reward_negative_scale: 0.1