params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  network:
    name: actor_critic
    separate: True
    #normalization: layer_norm
    space: 
      discrete:
    mlp:
      units: [256, 256]
      activation: relu
      initializer:
        name: default 
      regularizer:
        name:  'None'

  config:
    name: 6h_vs_8z_separate
    reward_shaper:
      scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    score_to_win: 20
    grad_norm: 0.5
    entropy_coef: 0.002
    truncate_grads: True
    env_name: smac
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    horizon_length: 128
    minibatch_size: 3072 # 6 * 512
    mini_epochs: 2
    critic_coef: 1
    lr_schedule: None
    kl_threshold: 0.05
    normalize_input: True
    use_action_masks: True
    ignore_dead_batches : False

    env_config:
      name: 6h_vs_8z
      central_value: False
      reward_only_positive: False
      obs_last_action: True
      frames: 1
      #flatten: False