params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  load_checkpoint: False
  load_path: 

  network:
    name: actor_critic
    separate: False
    space: 
      discrete:

    cnn:
      type: conv2d
      activation: relu
      initializer:
        name: orthogonal_initializer
        gain: 1.41421356237 
      regularizer:
        name: 'None'
      convs:    
        - filters: 32
          kernel_size: 8
          strides: 4
          padding: 0
        - filters: 64
          kernel_size: 4
          strides: 2
          padding: 0
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 0
      
    mlp:
      units: [512]
      activation: relu
      regularizer:
        name: 'None'
      initializer:
        name: orthogonal_initializer
        gain: 1.41421356237
  config:
    reward_shaper:
      min_val: -1
      max_val: 1
        
    normalize_advantage: True
    gamma: 0.99
    tau: 0.9
    learning_rate: 3e-4
    name: atari
    score_to_win: 900
    grad_norm: 10
    entropy_coef: 0.01
    truncate_grads: True
    env_name: BreakoutNoFrameskip-v4
    ppo: true
    e_clip: 0.2
    clip_value: True
    num_actors: 16
    steps_num: 128
    minibatch_size: 1024
    mini_epochs: 4
    critic_coef: 1
    lr_schedule:  None
    lr_threshold: 0.008
    normalize_input: False
    lr_schedule:  None
    lr_threshold: 0.01
    max_epochs: 20000

    player:
      render: True
      games_num: 2
      n_game_life: 5
      is_determenistic: False