params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  network:
    name: resnet_actor_critic
    require_rewards: True
    require_last_actions: True
    separate: False
    value_shape: 1
    space:
      discrete:

    cnn:
      permute_input: True
      conv_depths: [16, 32, 32]
      activation: relu
      initializer:
        name: default
      regularizer:
        name: 'None'

    mlp:
      units: [512]
      activation: relu
      regularizer:
        name: 'None'
      initializer:
        name: default
    rnn:
      name: lstm
      units: 256
      layers: 1

  config:
    env_name: atari_gym
    reward_shaper:
      min_val: -1
      max_val: 1
        
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    name: breakout_impala_lstm
    score_to_win: 900
    grad_norm: 0.5
    entropy_coef: 0.01
    truncate_grads: True

    e_clip: 0.2
    clip_value: True
    num_actors: 16
    horizon_length: 256
    minibatch_size: 512
    mini_epochs: 3
    critic_coef: 1
    lr_schedule:  None
    kl_threshold: 0.01
    normalize_input: False
    seq_length: 8

    # max_epochs: 5000
    env_config:
      skip: 4
      name: 'BreakoutNoFrameskip-v4'
      episode_life: True
      wrap_impala: True
    player:
      render: False
      games_num: 100
      n_game_life: 5
      deterministic: False
