params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c



  network:
    name: actor_critic
    separate: False
    space: 
      discrete:

    cnn:
      permute_input: False
      type: conv2d
      activation: relu
      initializer:
        name: glorot_normal_initializer
        gain: 1.4142 
      regularizer:
        name: 'None'
      convs:    
        - filters: 32
          kernel_size: 8
          strides: 4
          padding: 0
        - filters: 64
          kernel_size: 4
          strides: 2
          padding: 0
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 0
      
    mlp:
      units: [512]
      activation: relu
      regularizer:
        name: 'None'
      initializer:
        name: glorot_normal_initializer
        gain: 1.4142
  config:
    reward_shaper:
      #min_val: -1
      #max_val: 1
      scale_value: 0.01

    normalize_advantage: True
    gamma: 0.999
    tau: 0.95
    learning_rate: 5e-4
    name: pacman_ppo
    score_to_win: 100000
    grad_norm: 1
    entropy_coef: 0.01
    truncate_grads: True
    env_name: envpool
    e_clip: 0.2
    clip_value: False
    num_actors: 48
    horizon_length: 128
    minibatch_size: 768
    mini_epochs: 3
    critic_coef: 1
    #seq_length: 64
    lr_schedule: None #adaptive
    kl_threshold: 0.01
    #lr_schedule:  linear
    #schedule_entropy: True
    normalize_value: True
    normalize_input: False
    use_diagnostics: True
    max_epochs: 30000

    env_config:
      env_name: 'MsPacman-v5'
      episodic_life: True
      has_lives: True
    player:
        render: True
        games_num: 10
        n_game_life: 3
        deterministic: True
        render_sleep: 0.05