params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c



  network:
    name: actor_critic
    separate: False
    space: 
      discrete:

    cnn:
      type: conv2d
      activation: relu
      initializer:
        name: glorot_normal_initializer
        gain: 1.4142 
      regularizer:
        name: 'None'
      convs:    
        - filters: 32
          kernel_size: 8
          strides: 4
          padding: 0
        - filters: 64
          kernel_size: 4
          strides: 2
          padding: 0
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 0
      
    mlp:
      units: [512]
      activation: relu
      regularizer:
        name: 'None'
      initializer:
        name: glorot_normal_initializer
        gain: 1.4142 

  config:
    reward_shaper:
      #min_val: -1
      #max_val: 1
      scale_value: 1
        
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    name: pacman_ff_no_normalize
    score_to_win: 50000
    grad_norm: 0.5
    entropy_coef: 0.01
    truncate_grads: True
    env_name: atari_gym
    e_clip: 0.2
    clip_value: False
    num_actors: 16
    horizon_length: 256
    minibatch_size: 1024
    mini_epochs: 4
    critic_coef: 1
    lr_schedule:  linear
    schedule_entropy: True
    normalize_input: False
    normalize_value: True
    max_epochs: 20000
    env_config:
      skip: 4
      name: 'MsPacmanNoFrameskip-v4'
      episode_life: True
    player:
        render: True
        games_num: 10
        n_game_life: 3
        deterministic: True
        render_sleep: 0.05