params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  network:
    name: e2e_vision_actor_critic
    separate: False
    value_shape: 1
    space: 
      discrete:
  
    backbone:
      type: vit_b_16 #efficientnet_v2_s #convnext_tiny #vit_b_16 #resnet18 #resnet34
      pretrained: True
      permute_input: False
      freeze: True
      preprocess_image: True

      args:
        zero_init_residual: True
        norm_layer: None

    mlp:
      units: [256]
      activation: relu
      regularizer:
        name: None
      initializer:
        name: default

    rnn:
      name: lstm
      units: 512
      layers: 1
      before_mlp: True
  config:
    name: Pacman_vit_b_16_frozen
    env_name: envpool
    reward_shaper:
      min_val: -100
      max_val: 100

    mixed_precision: True
    normalize_input: False
    normalize_value: True
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 2e-4

    score_to_win: 100000
    grad_norm: 1.0
    entropy_coef: 0.01
    truncate_grads: True

    e_clip: 0.2
    clip_value: True
    save_best_after: 25
    save_frequency: 500
    num_actors: 64
    horizon_length: 128
    minibatch_size: 1024 #2048
    mini_epochs: 2
    critic_coef: 1
    lr_schedule: linear
    kl_threshold: 0.01
    use_diagnostics: True
    seq_length: 8
    max_epochs: 10000
    #weight_decay: 0.001

    env_config:
      env_name: MsPacman-v5
      episodic_life: True
      has_lives: True
      use_dict_obs_space: False #True
      stack_num: 1
      gray_scale: False
    player:
        render: True
        games_num: 10
        n_game_life: 1
        deterministic: True

