params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  load_checkpoint: False
  load_path: 

  network:
    name: actor_critic
    separate: False
    space: 
      discrete:

    cnn:
      type: conv2d
      activation: relu
      initializer:
        name: glorot_normal_initializer
        gain: 1.4142 
      regularizer:
        name: 'None'
      convs:    
        - filters: 32
          kernel_size: 8
          strides: 4
          padding: 0
        - filters: 64
          kernel_size: 4
          strides: 2
          padding: 0
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 0
      
    mlp:
      units: [512]
      activation: relu
      regularizer:
        name: 'None'
      initializer:
        name: glorot_normal_initializer
        gain: 1.4142 

  config:
    reward_shaper:
      min_val: -1
      max_val: 1
        
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    name: pacman_ff
    score_to_win: 900
    grad_norm: 0.5
    entropy_coef: 0.005
    truncate_grads: True
    env_name: MsPacmanNoFrameskip-v4
    ppo: true
    e_clip: 0.2
    clip_value: False
    num_actors: 16
    steps_num: 256
    minibatch_size: 1024
    mini_epochs: 4
    critic_coef: 1
    lr_schedule:  adaptive
    lr_threshold: 0.008
    normalize_input: False

    player:
        render: True
        games_num: 10
        n_game_life: 3
        is_determenistic: True