params:
  seed: 5
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      initializer:
        name: default

  config:
    name: HalfCheetah-v3
    env_name:  openai_gym
    score_to_win: 20000
    ppo: true
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    reward_shaper:
      scale_value: 0.1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95

    learning_rate: 3e-4
    lr_schedule: adaptive
    schedule_type: standard
    kl_threshold: 0.008
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True

    e_clip: 0.2
    clip_value: False
    num_actors: 64
    horizon_length: 256
    minibatch_size: 2048
    mini_epochs: 4
    critic_coef: 2
    bounds_loss_coef: 0.0
    max_epochs: 2000
    env_config:
      name: HalfCheetah-v3
      seed: 5

    player:
      render: True
      deterministic: True
      games_num: 100