params:
  seed: 7
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [512, 256, 128]
      activation: elu
      initializer:
        name: default

  config:
      name: Humanoid-v4_ray
      env_name: openai_gym
      score_to_win: 20000
      normalize_input: True
      normalize_value: True
      value_bootstrap: True
      reward_shaper:
        scale_value: 0.1
      normalize_advantage: True
      gamma: 0.99
      tau: 0.95

      learning_rate: 3e-4
      lr_schedule: adaptive
      kl_threshold: 0.008
      grad_norm: 1.0
      entropy_coef: 0.0
      truncate_grads: True
      e_clip: 0.2
      clip_value: True
      use_smooth_clamp: True
      bound_loss_type: regularisation
      bounds_loss_coef: 0.0005
      max_epochs: 2000
      num_actors: 64
      horizon_length: 128
      minibatch_size: 2048
      mini_epochs: 5
      critic_coef: 4

      env_config:
        name: Humanoid-v4
        seed: 5

      player:
        render: True