params:
  seed: 5
  algo:
    name: a2c_continuous
  model:
    name: continuous_a2c_logstd
  network:
    name: actor_critic_transformer
    separate: false
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: -1.0
        fixed_sigma: true
    mlp:
      units:
      - 128
      activation: elu
      initializer:
        name: default
    transformer:
      max_steps: 16
      n_layers: 2
      n_heads: 4
      n_kv_heads: 2
      ffn_hidden: 256
      memory: true
  config:
    name: Humanoid-v5_transformer_envpool
    env_name: envpool
    score_to_win: 20000
    normalize_input: true
    normalize_value: true
    value_bootstrap: true
    mixed_precision: true
    reward_shaper:
      scale_value: 0.1
    normalize_advantage: true
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: true
    e_clip: 0.2
    clip_value: true
    use_smooth_clamp: true
    bound_loss_type: regularisation
    bounds_loss_coef: 0.0005
    max_epochs: 2500
    num_actors: 64
    horizon_length: 128
    minibatch_size: 2048
    mini_epochs: 5
    critic_coef: 4
    env_config:
      env_name: Humanoid-v5
    player:
      render: false
    seq_length: 8
