params:
  seed: 5
  algo:
    name: mbppo_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      initializer:
        name: default
  model_network:
    name: env_model
    mlp:
      units: [512, 512, 512]
      activation: relu
      initializer:
          name: default
  config:
      reward_shaper:
        scale_value: 0.1
      normalize_advantage: True
      gamma: 0.995
      tau: 0.95

      learning_rate: 3e-4
      name: Ant-v4
      score_to_win: 10000

      grad_norm: 0.5
      entropy_coef: 0.0
      truncate_grads: True
      env_name:  envpool
      ppo: true
      e_clip: 0.2
      clip_value: False
      num_actors: 64
      horizon_length: 64
      minibatch_size: 1024
      mini_epochs: 4
      critic_coef: 1
      lr_schedule:  adaptive
      kl_threshold: 0.008
      schedule_type: 'standard'
      normalize_input: True
      normalize_value: True
      value_bootstrap: True
      bounds_loss_coef: 0.000
      max_epochs: 5000
      env_config:
        env_name: Ant-v4
        seed: 5

      player:
        render: True

  model_training_config:
    minibatch_size: 2048
    mini_epochs: 4
    learning_rate: 1e-4
    replay_buffer_size: 8192 #1048576 # 1024 * 1024
    weight_decay: 1e-5
    hold_out: 0.1
