params:
  seed: 5
  algo:
    name: sac

  model:
    name: soft_actor_critic

  network:
    name: soft_actor_critic
    separate: True
    space:
      continuous:
    mlp:
      units: [256, 128, 64]
      activation: relu
      
      initializer:
        name: default
    log_std_bounds: [-5, 2]

  config:
    name: Ant-v4_SAC
    env_name: envpool
    normalize_input: True
    reward_shaper:
      scale_value: 1.0

    max_epochs: 10000
    num_steps_per_episode: 8
    save_best_after: 500
    save_frequency: 10000
    gamma: 0.99
    init_alpha: 1
    alpha_lr: 5e-3
    actor_lr: 5e-4
    critic_lr: 5e-4
    critic_tau: 5e-3
    batch_size: 2048
    learnable_temperature: True
    num_warmup_steps: 10 # total number of warmup steps: num_actors * num_steps_per_episode * num_warmup_steps
    replay_buffer_size: 1000000
    num_actors: 64

    env_config:
      env_name: Ant-v4
      seed: 5
  