params:
  seed: 5
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      initializer:
        name: default

  config:
      name: PickCube_state
      env_name: maniskill
      reward_shaper:
        scale_value: 1.0
      normalize_input: True
      normalize_value: True
      value_bootstrap: True
      normalize_advantage: True
      gamma: 0.99
      tau: 0.95

      learning_rate: 3e-4
      lr_schedule: adaptive
      kl_threshold: 0.008
      grad_norm: 1.0
      entropy_coef: 0.0
      truncate_grads: True
      e_clip: 0.2
      clip_value: True
      use_smooth_clamp: True
      bound_loss_type: regularisation
      bounds_loss_coef: 0.0005
      max_epochs: 5000
      save_best_after: 25
      save_frequency: 100
      num_actors: 4096
      horizon_length: 16
      minibatch_size: 16384
      mini_epochs: 6
      critic_coef: 2

      env_config:
        env_name: PickCube-v1  # todo: add list of all envs
        observation_mode: state
        control_mode: pd_ee_delta_pose
        reward_mode: dense

      player:
        render: True