params:
  seed: 7

  #devices: [0, 0]

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
          scale: 0.02
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True

    cnn:
      permute_input: True
      type: conv2d
      activation: relu
      initializer:
        name: orthogonal_initializer
        gain: 1.41421356237 
      convs:    
        - filters: 32
          kernel_size: 8
          strides: 4
          padding: 0
        - filters: 64
          kernel_size: 4
          strides: 2
          padding: 0
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 0
      
    mlp:
      units: [256]
      activation: relu
      initializer:
        name: orthogonal_initializer
        gain: 1.41421356237
    rnn:
      name: 'lstm'
      units: 512
      layers: 1
      before_mlp: True
      layer_norm: True
  config:
    name: PickCube_RGB_Maniskill
    full_experiment_name: PickCube_RGB_Maniskill
    env_name: maniskill
    multi_gpu: False
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    normalize_advantage: True
    use_smooth_clamp: False
    reward_shaper:
      scale_value: 1.0
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-4
    lr_schedule: None #adaptive
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: 5000
    save_best_after: 100
    save_frequency: 50
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 8
    num_actors: 512
    minibatch_size: 2048
    mini_epochs: 2
    critic_coef: 2
    clip_value: True
    bounds_loss_coef: 0.0001

    env_config:
    # look at the https://maniskill.readthedocs.io/en/latest/user_guide/concepts/observation.html
      env_name: PickCube-v1
      obs_mode: "rgbd" 
      control_mode: "pd_ee_delta_pose" # there is also "pd_joint_delta_pos", ..
